import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type {
  DeveloperReport,
  AuditorReport,
  EndUserReport,
  ReportSummary,
} from "@/types";

type ReportType = "developer" | "auditor" | "end-user";

const REPORT_TYPE_LABELS: Record<ReportType, string> = {
  developer: "Developer Report",
  auditor: "Auditor Report",
  "end-user": "End-User Report",
};

const COLORS = {
  primary: [37, 99, 235] as [number, number, number],
  darkGray: [31, 41, 55] as [number, number, number],
  mediumGray: [107, 114, 128] as [number, number, number],
  lightGray: [243, 244, 246] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  critical: [220, 38, 38] as [number, number, number],
  serious: [234, 88, 12] as [number, number, number],
  moderate: [202, 138, 4] as [number, number, number],
  minor: [59, 130, 246] as [number, number, number],
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getDateString(): string {
  return new Date().toISOString().split("T")[0];
}

function severityColor(severity: string): [number, number, number] {
  switch (severity) {
    case "critical":
      return COLORS.critical;
    case "serious":
      return COLORS.serious;
    case "moderate":
      return COLORS.moderate;
    case "minor":
      return COLORS.minor;
    default:
      return COLORS.mediumGray;
  }
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  return text.substring(0, max - 3) + "...";
}

function scoreLabel(score: number): string {
  if (score >= 90) return "Excellent";
  if (score >= 70) return "Good";
  if (score >= 50) return "Needs Improvement";
  if (score >= 30) return "Poor";
  return "Critical";
}

// ---------------------------------------------------------------------------
// Header & Summary
// ---------------------------------------------------------------------------

function addHeader(
  doc: jsPDF,
  summary: ReportSummary,
  reportType: ReportType
): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(...COLORS.primary);
  doc.text("AWAE - Web Accessibility Evaluation Report", pageWidth / 2, 25, {
    align: "center",
  });

  // Report type subtitle
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.mediumGray);
  doc.text(REPORT_TYPE_LABELS[reportType], pageWidth / 2, 34, {
    align: "center",
  });

  // Divider
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.5);
  doc.line(20, 39, pageWidth - 20, 39);

  // Meta information
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.darkGray);
  doc.text(`Target URL: ${summary.targetUrl}`, 20, 48);
  doc.text(
    `Evaluation Date: ${new Date(summary.evaluationDate).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })}`,
    20,
    55
  );
  doc.text(`axe-core Version: ${summary.axeCoreVersion}`, 20, 62);

  // Score box
  const scoreX = pageWidth - 70;
  doc.setFillColor(...COLORS.lightGray);
  doc.roundedRect(scoreX, 43, 50, 24, 3, 3, "F");
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.primary);
  doc.text(`${summary.overallScore}`, scoreX + 25, 52, { align: "center" });
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.mediumGray);
  doc.text(scoreLabel(summary.overallScore), scoreX + 25, 61, {
    align: "center",
  });

  // Severity summary line
  const startY = 72;
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.darkGray);
  doc.text(
    `Total Violations: ${summary.totalViolations}   |   Critical: ${summary.criticalCount}   |   Serious: ${summary.seriousCount}   |   Moderate: ${summary.moderateCount}   |   Minor: ${summary.minorCount}`,
    20,
    startY
  );

  return startY + 10;
}

function addFooter(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(
      `Generated by AWAE  |  Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }
}

// ---------------------------------------------------------------------------
// Developer PDF
// ---------------------------------------------------------------------------

function generateDeveloperPdf(doc: jsPDF, report: DeveloperReport): void {
  let y = addHeader(doc, report.summary, "developer");

  // Section title
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.darkGray);
  doc.text("Violation Details", 20, y);
  y += 6;

  if (report.violations.length === 0) {
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(
      "No violations found. The page meets all WCAG 2.2 criteria tested.",
      20,
      y + 6
    );
    addFooter(doc);
    return;
  }

  // Summary violations table
  const tableBody = report.violations.map((v) => [
    v.ruleId,
    v.severity.charAt(0).toUpperCase() + v.severity.slice(1),
    `${v.wcagCriterion} (${v.wcagLevel})`,
    truncate(v.description, 80),
    truncate(v.elements.map((el) => el.selector).join("; "), 50),
    truncate(v.remediation, 80),
  ]);

  autoTable(doc, {
    startY: y,
    head: [
      ["Rule ID", "Severity", "WCAG", "Description", "Elements", "Remediation"],
    ],
    body: tableBody,
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 7,
      textColor: COLORS.darkGray,
    },
    alternateRowStyles: {
      fillColor: COLORS.lightGray,
    },
    columnStyles: {
      0: { cellWidth: 24 },
      1: { cellWidth: 18 },
      2: { cellWidth: 24 },
      3: { cellWidth: "auto" },
      4: { cellWidth: 40 },
      5: { cellWidth: "auto" },
    },
    margin: { left: 20, right: 20 },
    didParseCell(data) {
      if (data.section === "body" && data.column.index === 1) {
        const raw = String(data.cell.raw).toLowerCase();
        data.cell.styles.textColor = severityColor(raw);
        data.cell.styles.fontStyle = "bold";
      }
    },
  });

  // Detailed element breakdown pages
  for (const v of report.violations) {
    if (v.elements.length === 0) continue;

    doc.addPage();
    let detailY = 20;

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.primary);
    doc.text(`Rule: ${v.ruleId}`, 20, detailY);
    detailY += 7;

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.darkGray);
    doc.text(
      `Severity: ${v.severity}  |  WCAG: ${v.wcagCriterion} (${v.wcagLevel})  |  Principle: ${v.wcagPrinciple}`,
      20,
      detailY
    );
    detailY += 7;

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.mediumGray);
    const descLines = doc.splitTextToSize(v.description, 250);
    doc.text(descLines, 20, detailY);
    detailY += descLines.length * 4 + 4;

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.darkGray);
    doc.text("Remediation:", 20, detailY);
    detailY += 5;
    const remLines = doc.splitTextToSize(v.remediation, 250);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(remLines, 20, detailY);
    detailY += remLines.length * 4 + 6;

    const elemBody = v.elements.map((el, idx) => [
      String(idx + 1),
      truncate(el.selector, 60),
      truncate(el.htmlSnippet, 80),
      truncate(el.failureSummary, 60),
    ]);

    autoTable(doc, {
      startY: detailY,
      head: [["#", "Selector", "HTML Snippet", "Failure Summary"]],
      body: elemBody,
      headStyles: {
        fillColor: severityColor(v.severity),
        textColor: COLORS.white,
        fontSize: 8,
        fontStyle: "bold",
      },
      bodyStyles: {
        fontSize: 7,
        textColor: COLORS.darkGray,
        font: "courier",
      },
      alternateRowStyles: {
        fillColor: COLORS.lightGray,
      },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 55 },
        2: { cellWidth: "auto" },
        3: { cellWidth: "auto" },
      },
      margin: { left: 20, right: 20 },
    });
  }

  addFooter(doc);
}

// ---------------------------------------------------------------------------
// Auditor PDF
// ---------------------------------------------------------------------------

function generateAuditorPdf(doc: jsPDF, report: AuditorReport): void {
  let y = addHeader(doc, report.summary, "auditor");

  // Principle breakdown
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.darkGray);
  doc.text("WCAG 2.2 Principle Breakdown", 20, y);
  y += 6;

  const principleBody = report.principleBreakdown.map((p) => [
    p.principle,
    String(p.totalCriteria),
    String(p.passedCriteria),
    String(p.failedCriteria),
    `${p.compliancePercentage.toFixed(1)}%`,
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Principle", "Total Criteria", "Passed", "Failed", "Compliance"]],
    body: principleBody,
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontSize: 9,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 8,
      textColor: COLORS.darkGray,
    },
    alternateRowStyles: {
      fillColor: COLORS.lightGray,
    },
    margin: { left: 20, right: 20 },
    didParseCell(data) {
      if (data.section === "body" && data.column.index === 4) {
        const val = parseFloat(String(data.cell.raw));
        if (val >= 90) data.cell.styles.textColor = [34, 197, 94];
        else if (val >= 70) data.cell.styles.textColor = [132, 204, 22];
        else if (val >= 50) data.cell.styles.textColor = [245, 158, 11];
        else data.cell.styles.textColor = [239, 68, 68];
        data.cell.styles.fontStyle = "bold";
      }
    },
  });

  // Compliance Matrix on new page
  doc.addPage();
  let matrixY = 20;

  doc.setFontSize(14);
  doc.setTextColor(...COLORS.darkGray);
  doc.text("Compliance Matrix", 20, matrixY);
  matrixY += 6;

  const matrixBody = report.complianceMatrix.map((c) => [
    c.criterion,
    truncate(c.title, 40),
    c.level,
    c.principle,
    c.status === "pass" ? "Pass" : c.status === "fail" ? "Fail" : "Not Tested",
    String(c.violationCount),
  ]);

  autoTable(doc, {
    startY: matrixY,
    head: [
      ["Criterion", "Title", "Level", "Principle", "Status", "Violations"],
    ],
    body: matrixBody,
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 7,
      textColor: COLORS.darkGray,
    },
    alternateRowStyles: {
      fillColor: COLORS.lightGray,
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: "auto" },
      2: { cellWidth: 15 },
      3: { cellWidth: 28 },
      4: { cellWidth: 22 },
      5: { cellWidth: 20 },
    },
    margin: { left: 20, right: 20 },
    didParseCell(data) {
      if (data.section === "body" && data.column.index === 4) {
        const status = String(data.cell.raw);
        if (status === "Pass") {
          data.cell.styles.textColor = [34, 197, 94];
          data.cell.styles.fontStyle = "bold";
        } else if (status === "Fail") {
          data.cell.styles.textColor = [239, 68, 68];
          data.cell.styles.fontStyle = "bold";
        } else {
          data.cell.styles.textColor = COLORS.mediumGray;
        }
      }
    },
  });

  // Violations table on new page
  doc.addPage();
  let violY = 20;

  doc.setFontSize(14);
  doc.setTextColor(...COLORS.darkGray);
  doc.text("Violations", 20, violY);
  violY += 6;

  if (report.violations.length === 0) {
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text("No violations found.", 20, violY + 6);
  } else {
    const violBody = report.violations.map((v) => [
      v.ruleId,
      v.severity.charAt(0).toUpperCase() + v.severity.slice(1),
      `${v.wcagCriterion} (${v.wcagLevel})`,
      v.wcagPrinciple,
      String(v.instanceCount),
      truncate(v.formalDescription, 80),
    ]);

    autoTable(doc, {
      startY: violY,
      head: [
        [
          "Rule ID",
          "Severity",
          "WCAG",
          "Principle",
          "Instances",
          "Description",
        ],
      ],
      body: violBody,
      headStyles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontSize: 8,
        fontStyle: "bold",
      },
      bodyStyles: {
        fontSize: 7,
        textColor: COLORS.darkGray,
      },
      alternateRowStyles: {
        fillColor: COLORS.lightGray,
      },
      margin: { left: 20, right: 20 },
      didParseCell(data) {
        if (data.section === "body" && data.column.index === 1) {
          const raw = String(data.cell.raw).toLowerCase();
          data.cell.styles.textColor = severityColor(raw);
          data.cell.styles.fontStyle = "bold";
        }
      },
    });
  }

  addFooter(doc);
}

// ---------------------------------------------------------------------------
// End-User PDF
// ---------------------------------------------------------------------------

function generateEndUserPdf(doc: jsPDF, report: EndUserReport): void {
  let y = addHeader(doc, report.summary, "end-user");

  const pageWidth = doc.internal.pageSize.getWidth();

  // Score summary
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.darkGray);
  doc.text("Accessibility Score Overview", 20, y);
  y += 10;

  doc.setFontSize(28);
  doc.setTextColor(...COLORS.primary);
  doc.text(`${report.score}/100`, pageWidth / 2, y, { align: "center" });
  y += 10;

  doc.setFontSize(14);
  doc.text(report.scoreLabel, pageWidth / 2, y, { align: "center" });
  y += 14;

  // Score interpretation
  let interpretation: string;
  if (report.score >= 90) {
    interpretation =
      "This website demonstrates excellent accessibility. Most users, including those who rely on assistive technologies, should be able to navigate and use the content effectively.";
  } else if (report.score >= 70) {
    interpretation =
      "This website has good overall accessibility but there are some areas that could be improved. Some users with disabilities may encounter occasional difficulties.";
  } else if (report.score >= 50) {
    interpretation =
      "This website needs accessibility improvements. Users who rely on assistive technologies such as screen readers or keyboard navigation may face significant barriers.";
  } else if (report.score >= 30) {
    interpretation =
      "This website has poor accessibility. Many users with disabilities will encounter serious barriers that prevent them from using the site effectively.";
  } else {
    interpretation =
      "This website has critical accessibility issues. The site is largely inaccessible to users who depend on assistive technologies, and immediate remediation is strongly recommended.";
  }

  const interpLines = doc.splitTextToSize(interpretation, pageWidth - 40);
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.mediumGray);
  doc.text(interpLines, 20, y);
  y += interpLines.length * 5 + 10;

  // Category summaries
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.darkGray);
  doc.text("Accessibility Categories", 20, y);
  y += 6;

  if (report.categories.length > 0) {
    const catBody = report.categories.map((c) => [
      c.name,
      `${c.score}/100`,
      String(c.issueCount),
      truncate(c.description, 80),
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Category", "Score", "Issues", "Description"]],
      body: catBody,
      headStyles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontSize: 9,
        fontStyle: "bold",
      },
      bodyStyles: {
        fontSize: 8,
        textColor: COLORS.darkGray,
      },
      alternateRowStyles: {
        fillColor: COLORS.lightGray,
      },
      columnStyles: {
        0: { cellWidth: 35, fontStyle: "bold" },
        1: { cellWidth: 22 },
        2: { cellWidth: 18 },
        3: { cellWidth: "auto" },
      },
      margin: { left: 20, right: 20 },
    });
  }

  // Priority actions on new page
  if (report.priorities.length > 0) {
    doc.addPage();
    let priY = 20;

    doc.setFontSize(14);
    doc.setTextColor(...COLORS.darkGray);
    doc.text("Priority Actions", 20, priY);
    priY += 8;

    doc.setFontSize(10);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(
      "The following priorities are recommended to improve the accessibility of this website:",
      20,
      priY
    );
    priY += 10;

    for (let i = 0; i < report.priorities.length; i++) {
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.darkGray);

      const lines = doc.splitTextToSize(
        `${i + 1}. ${report.priorities[i]}`,
        pageWidth - 40
      );
      doc.text(lines, 20, priY);
      priY += lines.length * 5 + 4;

      // Add page if running out of space
      if (priY > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
        priY = 20;
      }
    }
  }

  addFooter(doc);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function exportToPdf(
  report: DeveloperReport | AuditorReport | EndUserReport,
  reportType: ReportType
): void {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  switch (reportType) {
    case "developer":
      generateDeveloperPdf(doc, report as DeveloperReport);
      break;
    case "auditor":
      generateAuditorPdf(doc, report as AuditorReport);
      break;
    case "end-user":
      generateEndUserPdf(doc, report as EndUserReport);
      break;
  }

  const filename = `awae-${reportType}-report-${getDateString()}.pdf`;
  doc.save(filename);
}
